# Generated by Django 3.0 on 2021-03-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=3)),
                ('flat_no', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('parking', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Self'), (1, 'Rented')])),
                ('society_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
